source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-github-metadata", "~> 2.16"

# Windows / JRuby compatibility
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
gem "wdm", "~> 0.1", platforms: [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
